# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PlotGui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(700, 0, 201, 536))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Peaks = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Peaks.setObjectName("Peaks")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.Peaks)
        self.exportPeaks = QtWidgets.QPushButton(self.formLayoutWidget)
        self.exportPeaks.setObjectName("exportPeaks")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.exportPeaks)
        self.bClear = QtWidgets.QPushButton(self.formLayoutWidget)
        self.bClear.setObjectName("bClear")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bClear)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Peaks_2 = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Peaks_2.setObjectName("Peaks_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.Peaks_2)
        self.clearNotes = QtWidgets.QPushButton(self.formLayoutWidget)
        self.clearNotes.setObjectName("clearNotes")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.clearNotes)
        self.plotLabelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.plotLabelLabel.setObjectName("plotLabelLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.plotLabelLabel)
        self.plotLabelLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.plotLabelLineEdit.setObjectName("plotLabelLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.plotLabelLineEdit)
        self.exportNotes = QtWidgets.QPushButton(self.formLayoutWidget)
        self.exportNotes.setObjectName("exportNotes")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.exportNotes)
        self.setLabel = QtWidgets.QPushButton(self.formLayoutWidget)
        self.setLabel.setObjectName("setLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.setLabel)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotframe = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.plotframe.setObjectName("plotframe")
        self.horizontalLayout.addWidget(self.plotframe)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 510, 101, 73))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.showIrBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.showIrBox.setObjectName("showIrBox")
        self.gridLayout.addWidget(self.showIrBox, 2, 0, 1, 1)
        self.showVisBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.showVisBox.setObjectName("showVisBox")
        self.gridLayout.addWidget(self.showVisBox, 3, 0, 1, 1)
        self.normalizedBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.normalizedBox.setObjectName("normalizedBox")
        self.gridLayout.addWidget(self.normalizedBox, 1, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(300, 510, 391, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pickingModeBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.pickingModeBox.setObjectName("pickingModeBox")
        self.horizontalLayout_2.addWidget(self.pickingModeBox)
        self.bIntegrate = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.bIntegrate.setObjectName("bIntegrate")
        self.horizontalLayout_2.addWidget(self.bIntegrate)
        self.bApply = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.bApply.setObjectName("bApply")
        self.horizontalLayout_2.addWidget(self.bApply)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(130, 510, 127, 94))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rootBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.rootBox.setObjectName("rootBox")
        self.gridLayout_2.addWidget(self.rootBox, 2, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 3, 0, 1, 1)
        self.smoothBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.smoothBox.setObjectName("smoothBox")
        self.gridLayout_2.addWidget(self.smoothBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Peaks and Integrals"))
        self.exportPeaks.setText(_translate("MainWindow", "Export"))
        self.bClear.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "Notes"))
        self.clearNotes.setText(_translate("MainWindow", "Clear"))
        self.plotLabelLabel.setText(_translate("MainWindow", "Plot label"))
        self.exportNotes.setText(_translate("MainWindow", "Export"))
        self.setLabel.setText(_translate("MainWindow", "Set"))
        self.showIrBox.setText(_translate("MainWindow", "show IR"))
        self.showVisBox.setText(_translate("MainWindow", "show Vis"))
        self.normalizedBox.setText(_translate("MainWindow", "normalized"))
        self.pickingModeBox.setText(_translate("MainWindow", "Picking Mode"))
        self.bIntegrate.setText(_translate("MainWindow", "Integrate"))
        self.bApply.setText(_translate("MainWindow", "Apply"))
        self.rootBox.setText(_translate("MainWindow", "square root"))
        self.checkBox_6.setText(_translate("MainWindow", "normalized to highest"))
        self.smoothBox.setText(_translate("MainWindow", "smooth"))

