# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SFGPlot.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(700, 20, 201, 536))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.fullNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.fullNameLabel.setObjectName("fullNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fullNameLabel)
        self.fullNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fullNameLineEdit.setObjectName("fullNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fullNameLineEdit)
        self.dateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.dateLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dateLineEdit.setObjectName("dateLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateLineEdit)
        self.surfactantLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.surfactantLabel.setObjectName("surfactantLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.surfactantLabel)
        self.surfactantLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.surfactantLineEdit.setObjectName("surfactantLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.surfactantLineEdit)
        self.spreadingVolumeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.spreadingVolumeLabel.setObjectName("spreadingVolumeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.spreadingVolumeLabel)
        self.spreadingVolumeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.spreadingVolumeLineEdit.setObjectName("spreadingVolumeLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spreadingVolumeLineEdit)
        self.sensitizerLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sensitizerLabel.setObjectName("sensitizerLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sensitizerLabel)
        self.sensitizerLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sensitizerLineEdit.setObjectName("sensitizerLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sensitizerLineEdit)
        self.spreadingVolumeLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.spreadingVolumeLabel_2.setObjectName("spreadingVolumeLabel_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.spreadingVolumeLabel_2)
        self.spreadingVolumeLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.spreadingVolumeLineEdit_2.setObjectName("spreadingVolumeLineEdit_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spreadingVolumeLineEdit_2)
        self.photolysisLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.photolysisLabel.setObjectName("photolysisLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.photolysisLabel)
        self.photolysisLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.photolysisLineEdit.setObjectName("photolysisLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.photolysisLineEdit)
        self.specralRangeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.specralRangeLabel.setObjectName("specralRangeLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.specralRangeLabel)
        self.specralRangeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.specralRangeLineEdit.setObjectName("specralRangeLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.specralRangeLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.commentLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.commentLabel.setObjectName("commentLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.commentLabel)
        self.Comment = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.Comment.setObjectName("Comment")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.Comment)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Peaks = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Peaks.setObjectName("Peaks")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.Peaks)
        self.bExport = QtWidgets.QPushButton(self.formLayoutWidget)
        self.bExport.setObjectName("bExport")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.bExport)
        self.bClear = QtWidgets.QPushButton(self.formLayoutWidget)
        self.bClear.setObjectName("bClear")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.bClear)
        self.plotLabelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.plotLabelLabel.setObjectName("plotLabelLabel")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.plotLabelLabel)
        self.plotLabelLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.plotLabelLineEdit.setObjectName("plotLabelLineEdit")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.plotLabelLineEdit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(690, 0, 47, 13))
        self.label.setObjectName("label")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(730, 650, 174, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.totalSpectraCountLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.totalSpectraCountLineEdit.setObjectName("totalSpectraCountLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.totalSpectraCountLineEdit)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.totalSpectraCountLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.totalSpectraCountLabel.setObjectName("totalSpectraCountLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.totalSpectraCountLabel)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotframe = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.plotframe.setObjectName("plotframe")
        self.horizontalLayout.addWidget(self.plotframe)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(590, 560, 101, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(400, 510, 293, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bRefresh = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.bRefresh.setObjectName("bRefresh")
        self.horizontalLayout_2.addWidget(self.bRefresh)
        self.bIntegrate = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.bIntegrate.setObjectName("bIntegrate")
        self.horizontalLayout_2.addWidget(self.bIntegrate)
        self.cStacked = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.cStacked.setObjectName("cStacked")
        self.horizontalLayout_2.addWidget(self.cStacked)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(700, 560, 201, 75))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lSpeclist = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.lSpeclist.setObjectName("lSpeclist")
        self.horizontalLayout_3.addWidget(self.lSpeclist)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 560, 101, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bNext = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bNext.setObjectName("bNext")
        self.verticalLayout_3.addWidget(self.bNext)
        self.bPrevious = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bPrevious.setObjectName("bPrevious")
        self.verticalLayout_3.addWidget(self.bPrevious)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fullNameLabel.setText(_translate("MainWindow", "Full name"))
        self.dateLabel.setText(_translate("MainWindow", "Date"))
        self.surfactantLabel.setText(_translate("MainWindow", "Surfactant"))
        self.spreadingVolumeLabel.setText(_translate("MainWindow", "Surf. volume"))
        self.sensitizerLabel.setText(_translate("MainWindow", "Sensitizer"))
        self.spreadingVolumeLabel_2.setText(_translate("MainWindow", "Sens volume"))
        self.photolysisLabel.setText(_translate("MainWindow", "Photolysis"))
        self.specralRangeLabel.setText(_translate("MainWindow", "Specral range"))
        self.commentLabel.setText(_translate("MainWindow", "Comment"))
        self.label_2.setText(_translate("MainWindow", "Peaks"))
        self.bExport.setText(_translate("MainWindow", "Export"))
        self.bClear.setText(_translate("MainWindow", "Clear"))
        self.plotLabelLabel.setText(_translate("MainWindow", "Plot label"))
        self.label.setText(_translate("MainWindow", "current"))
        self.pushButton.setText(_translate("MainWindow", "Select"))
        self.totalSpectraCountLabel.setText(_translate("MainWindow", "total spectra count"))
        self.checkBox_2.setText(_translate("MainWindow", "show IR"))
        self.checkBox_3.setText(_translate("MainWindow", "show Vis"))
        self.checkBox.setText(_translate("MainWindow", "normalized"))
        self.bRefresh.setText(_translate("MainWindow", "Refresh"))
        self.bIntegrate.setText(_translate("MainWindow", "Integrate"))
        self.cStacked.setText(_translate("MainWindow", "stack"))
        self.bNext.setText(_translate("MainWindow", "Next"))
        self.bPrevious.setText(_translate("MainWindow", "Previos"))

